# Generated by Django 3.2 on 2023-03-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('phno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('tname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='app1.teacher')),
            ],
        ),
    ]
